# -*- coding: utf-8 -*-
"""美股代碼 -> 中文簡稱對照表(涵蓋前150名+題材標籤公司)"""
NAME_ZH = {
    "MRVL": "邁威爾科技", "MU": "美光科技", "NVDA": "輝達(NVIDIA)", "SPCX": "SpaceX",
    "INTC": "英特爾", "SNDK": "Sandisk", "AAPL": "蘋果", "AMD": "超微(AMD)",
    "TSLA": "特斯拉", "MSFT": "微軟", "AVGO": "博通", "AMZN": "亞馬遜",
    "META": "Meta(原Facebook)", "GOOGL": "谷歌(Alphabet A)", "ARM": "Arm控股", "WDC": "威騰電子",
    "FLEX": "偉創力", "TSM": "台積電ADR", "GOOG": "谷歌(Alphabet C)", "QCOM": "高通",
    "NBIS": "Nebius", "AMAT": "應用材料", "ALAB": "Astera Labs", "STX": "希捷科技",
    "LRCX": "科林研發(Lam Research)", "CRM": "Salesforce", "TER": "泰瑞達(Teradyne)", "CRWV": "CoreWeave",
    "RKLB": "火箭實驗室(Rocket Lab)", "NFLX": "網飛(Netflix)", "PLTR": "Palantir", "TXN": "德州儀器",
    "LITE": "朗美通(Lumentum)", "KLAC": "科磊(KLA)", "XOM": "埃克森美孚", "JPM": "摩根大通",
    "DELL": "戴爾", "CSCO": "思科", "CAT": "卡特彼勒", "ORCL": "甲骨文(Oracle)",
    "ACN": "埃森哲(Accenture)", "BE": "Bloom Energy", "ADI": "亞德諾(Analog Devices)", "GS": "高盛",
    "LLY": "禮來(Eli Lilly)", "V": "Visa", "GEV": "GE Vernova", "UNH": "聯合健康(UnitedHealth)",
    "ASML": "艾司摩爾(ASML)", "APP": "AppLovin", "GLW": "康寧(Corning)", "BRK/B": "巴菲特控股(伯克希爾B)",
    "JNJ": "嬌生(Johnson & Johnson)", "WMT": "沃爾瑪", "HOOD": "Robinhood", "C": "花旗集團",
    "IBM": "IBM", "MSTR": "Strategy(原MicroStrategy)", "BAC": "美國銀行", "KO": "可口可樂",
    "ABT": "雅培(Abbott)", "CRWD": "CrowdStrike", "COST": "好市多(Costco)", "HD": "家得寶(Home Depot)",
    "PANW": "Palo Alto Networks", "NOW": "ServiceNow", "ROKU": "Roku", "MRK": "默克(Merck)",
    "CVX": "雪佛龍(Chevron)", "MA": "萬事達卡(Mastercard)", "CDE": "Coeur Mining", "AZO": "AutoZone",
    "BKNG": "Booking Holdings", "VRSK": "Verisk", "ADBE": "Adobe", "MPWR": "萬代半導體(MPS)",
    "WFC": "富國銀行", "PFE": "輝瑞(Pfizer)", "VZ": "威訊(Verizon)", "COHR": "Coherent",
    "SUNB": "Sunbelt Rentals", "SMTC": "Semtech", "GE": "GE航太(GE Aerospace)", "AMGN": "安進(Amgen)",
    "CDNS": "鏗騰電子(Cadence)", "PEP": "百事(PepsiCo)", "AAOI": "應用光電", "INTU": "Intuit",
    "CTSH": "高知特(Cognizant)", "FTNT": "飛塔(Fortinet)", "MS": "摩根士丹利", "LIN": "林德集團(Linde)",
    "PG": "寶僑(P&G)", "ASTS": "AST SpaceMobile", "CRDO": "Credo Technology", "HPE": "慧與(HPE)",
    "SANM": "Sanmina", "SCHW": "嘉信理財(Charles Schwab)", "NXPI": "恩智浦(NXP)", "COP": "康菲石油",
    "ON": "安森美(onsemi)", "VRT": "維諦技術(Vertiv)", "DIS": "迪士尼", "SATS": "EchoStar",
    "IREN": "IREN", "VIAV": "Viavi Solutions", "TMUS": "T-Mobile美國", "CHTR": "Charter通訊",
    "MCD": "麥當勞", "INSM": "Insmed", "CVS": "CVS Health", "APH": "安費諾(Amphenol)",
    "PM": "菲利普莫里斯(萬寶路)", "SMCI": "美超微(Super Micro)", "ABBV": "艾伯維(AbbVie)", "T": "美國電話電報(AT&T)",
    "ZS": "Zscaler", "PGR": "前進保險(Progressive)", "LMT": "洛克希德馬丁", "AAL": "美國航空",
    "SLB": "斯倫貝謝(SLB)", "NEM": "紐蒙特礦業", "BA": "波音", "UBER": "Uber",
    "CEG": "星座能源(Constellation Energy)", "SO": "南方公司(Southern Co.)", "DDOG": "Datadog", "ANET": "Arista Networks",
    "MCK": "麥克森(McKesson)", "PWR": "昆塔服務(Quanta Services)", "CIEN": "Ciena", "SNOW": "Snowflake",
    "MDT": "美敦力(Medtronic)", "ISRG": "直覺外科(Intuitive Surgical)", "ADSK": "歐特克(Autodesk)", "TRV": "旅行者保險",
    "GILD": "吉利德科學(Gilead)", "OMC": "宏盟集團(Omnicom)", "TTWO": "Take-Two互動", "CME": "芝商所(CME Group)",
    "BMY": "百時美施貴寶", "NOK": "諾基亞(Nokia)", "CBRS": "Cerebras Systems", "NEE": "新紀元能源(NextEra)",
    "CMCSA": "康卡斯特(Comcast)", "WELL": "Welltower", "RTX": "雷神技術(RTX)", "POOL": "Pool Corp",
    "COF": "第一資本(Capital One)", "MCHP": "微芯科技(Microchip)", "COIN": "Coinbase", "ETN": "伊頓(Eaton)",
    "GD": "通用動力", "NTAP": "NetApp", "NOC": "諾斯洛普格魯曼", "HWM": "Howmet Aerospace",
    "CIFR": "Cipher Mining", "IONQ": "IonQ", "ENTG": "英特格(Entegris)", "AXTI": "AXT",
    "JBL": "捷普(Jabil)", "TDG": "Transdigm", "FSLR": "第一太陽能(First Solar)", "Q": "Qnity Electronics(DuPont分拆)",
    "WULF": "TeraWulf", "OKLO": "Oklo", "MKSI": "MKS儀器", "BMNR": "BitMine Immersion",
    "AXON": "Axon Enterprise(泰瑟槍)", "CW": "Curtiss-Wright", "SMR": "NuScale Power", "LHX": "L3Harris",
    "FN": "Fabrinet", "CLS": "Celestica", "QBTS": "D-Wave量子", "RGTI": "Rigetti量子",
    "TEL": "泰科電子(TE Connectivity)", "VSH": "Vishay", "ENPH": "Enphase Energy", "TSEM": "Tower Semiconductor",
    "QS": "QuantumScape", "SWKS": "思佳訊(Skyworks)", "RDW": "Redwire", "UMC": "聯電ADR",
    "ASX": "日月光ADR", "FFIV": "F5", "RMBS": "Rambus", "ONTO": "Onto Innovation",
    "TTMI": "TTM Technologies", "NVTS": "Navitas Semiconductor", "WOLF": "Wolfspeed", "ROK": "羅克韋爾自動化(Rockwell)",
    "HUT": "Hut 8", "CORZ": "Core Scientific", "SIMO": "群聯ADR(Silicon Motion)", "SITM": "SiTime",
    "LSCC": "萊迪思半導體(Lattice)", "AMKR": "安靠科技(Amkor)", "KRMN": "Karman控股", "MARA": "MARA Holdings",
    "JOBY": "Joby Aviation", "LUNR": "Intuitive Machines", "LEU": "Centrus Energy", "FLY": "Firefly Aerospace",
    "MXL": "MaxLinear", "RIOT": "Riot Platforms", "TXT": "德事隆(Textron)", "KTOS": "Kratos Defense",
    "INFQ": "Infleqtion", "QNT": "Quantinuum", "FCEL": "FuelCell Energy", "HII": "亨廷頓英格爾斯(造船)",
    "NVMI": "Nova Ltd", "CLSK": "CleanSpark", "ACMR": "中微半導體美股(ACM Research)", "XE": "X-Energy",
}
